---
- name: Delete source files
  ansible.windows.win_file:
    path: "{{ rl_mssql_temp_folder }}"
    state: absent

- name: Remove DSC modules
  ansible.windows.win_file:
    path: "C:\\Program Files\\WindowsPowerShell\\Modules\\SqlServerDsc"
    state: absent
