---
- name: Set SQL Server Max Memory
  ansible.windows.win_dsc:
    resource_name: SqlMemory
    Ensure: "Present"
    DynamicAlloc: true
    ServerName: "localhost"
    InstanceName: "{{ rl_mssql_instance_name }}"

- name: Set SQL Server instance maxdop
  ansible.windows.win_dsc:
    resource_name: SQLMaxDop
    DynamicAlloc: true
    ServerName: "localhost"
    InstanceName: "{{ rl_mssql_instance_name }}"

- name: Set backup compression
  ansible.windows.win_dsc:
    resource_name: SQLConfiguration
    OptionName: "backup compression default"
    OptionValue: 1
    ServerName: "localhost"
    InstanceName: "{{ rl_mssql_instance_name }}"

- name: Set SQL Server instance cost threshold for parallelism
  ansible.windows.win_dsc:
    resource_name: SQLConfiguration
    OptionName: "cost threshold for parallelism"
    OptionValue: 50
    ServerName: "localhost"
    InstanceName: "{{ rl_mssql_instance_name }}"

- name: Set SQL Server instance port
  ansible.windows.win_dsc:
    resource_name: SqlProtocolTcpIp
    IpAddressGroup: "IPAll"
    Enabled: true
    SuppressRestart: false
    TCPPort: "{{ rl_mssql_instance_port }}"
    ServerName: "localhost"
    InstanceName: "{{ rl_mssql_instance_name }}"

- name: Set SQL Server instance number of error logs to 30
  ansible.windows.win_dsc:
    resource_name: SqlScript
    Id: "SetMaxNumErrorLogs"
    SetFilePath: "{{ rl_mssql_temp_folder }}\\Set-NumErrorLogs.sql"
    GetFilePath: "{{ rl_mssql_temp_folder }}\\Get-NumErrorLogs.sql"
    TestFilePath: "{{ rl_mssql_temp_folder }}\\Test-NumErrorLogs.sql"
    QueryTimeout: 600
    ServerName: "localhost"
    InstanceName: "{{ rl_mssql_instance_name }}"
    Encrypt: "Optional"

- name: Set SQL Server agent job history max rows to unlimited
  ansible.windows.win_dsc:
    resource_name: SqlScript
    Id: "SetJobHistoryMaxRows"
    SetFilePath: "{{ rl_mssql_temp_folder }}\\Set-JobHistoryMaxRows.sql"
    GetFilePath: "{{ rl_mssql_temp_folder }}\\Get-JobHistoryMaxRows.sql"
    TestFilePath: "{{ rl_mssql_temp_folder }}\\Test-JobHistoryMaxRows.sql"
    QueryTimeout: 600
    ServerName: "localhost"
    InstanceName: "{{ rl_mssql_instance_name }}"
    Encrypt: "Optional"

- name: Add trace flag 3226
  ansible.windows.win_dsc:
    resource_name: SqlTraceFlag
    ServerName: "localhost"
    InstanceName: "{{ rl_mssql_instance_name }}"
    TraceFlagsToInclude: "3226"
    RestartService: true
