---
- name: Get disk facts from Windows hosts
  community.windows.win_disk_facts:

- name: Initialize disks
  community.windows.win_initialize_disk:
    disk_number: "{{ item.number }}"
  when:
    - item.partition_style == 'RAW'
    - item.bus_type == 'SAS'
  loop: "{{ ansible_facts.disks }}"
  loop_control:
    label: "{{ item.unique_id }}"

- name: Partition disks
  community.windows.win_partition:
    drive_letter: "{{ item.letter }}"
    disk_number: "{{ item.number }}"
    partition_size: -1 # Use the whole disk
  loop: "{{ sql_install_disks_to_format }}"

- name: Format disks
  community.windows.win_format:
    drive_letter: "{{ item.letter }}"
    file_system: REFS
    new_label: "{{ item.label }}"
    allocation_unit_size: 65536
  loop: "{{ sql_install_disks_to_format }}"