---
- name: SQL Server SA password
  ansible.builtin.set_fact:
    sa_password_switch: "{{ '/SAPWD={{ sql_install_sapwd }}' }}"

- name: Install instance
  ansible.windows.win_command:
    cmd: "{{ disk_image_out.results[0].mount_paths[0] }}setup.exe /ConfigurationFile={{ sql_install_temp_folder }}\\Configuration.ini {{ sa_password_switch }}"
  # no_log: true
