---
- name: Enable CLR needed for SSISDB
  ansible.windows.win_dsc:
    resource_name: SQLConfiguration
    OptionName: "clr enabled"
    OptionValue: 1
    ServerName: "localhost"
    InstanceName: "{{ rl_mssql_instance_name }}"

- name: Setup the Integration Services Catalog (Conditional)
  vars:
    # Use the template lookup to read the PowerShell script content.
    # The script is treated as a Jinja2 template to allow for variable substitution if needed in the future.
    ssis_script_content: "{{ lookup('file', 'integration_services_catalog.ps1') }}"
  ansible.windows.win_dsc:
    resource_name: Script
    GetScript: |
      # Inject the entire script content, then call the function.
      {{ ssis_script_content }}
      Get-SsisCatalog -InstanceName '{{ instance_name_var }}'
    TestScript: |
      # Inject the entire script content, then call the function.
      {{ ssis_script_content }}
      Test-SsisCatalog -InstanceName '{{ instance_name_var }}'
    SetScript: |
      # Inject the entire script content, then call the function with all parameters.
      {{ ssis_script_content }}
      Set-SsisCatalog -InstanceName '{{ instance_name_var }}' -Password '{{ rl_mssql_ssisdb_password }}' -SqlVersion '{{ rl_mssql_version }}'

