---
- name: Mount the iso
  community.windows.win_disk_image:
    image_path: "{{ sql_install_temp_folder }}\\{{ item.name }}"
    state: present
  register: disk_image_out
  loop: "{{ sql_install_iso_source }}"

# - name: Use the mounted path
#   debug:
#     msg: "The mounted path is {{ disk_image_out.results[0].mount_paths }}"

- name: Wait for Iso to mount
  ansible.builtin.pause:
    seconds: 3
  when: disk_image_out.changed

      # - name: Mount ISO
      # community.windows.win_disk_image:
      #   image_path: 'C:\temp\enu_sql_server_2022_developer_edition_x64_dvd_7cacf733.iso'
      #   state: present
      # register: disk_image_out
