---
- name: Mount the iso
  community.windows.win_disk_image:
    image_path: "{{ sql_install_temp_folder }}\\{{ item.name }}"
    state: present
  register: disk_image_out
  loop: "{{ sql_install_iso_source }}"

- name: Wait for Iso to mount
  ansible.builtin.pause:
    seconds: 3
  when: disk_image_out.changed
  
