---
- name: Create the DBA team operator
  ansible.windows.win_dsc:
    resource_name: SqlAgentOperator
    Ensure: "Present"
    Name: "{{ item.name }}"
    EmailAddress: "{{ item.email }}"
    ServerName: "localhost"
    InstanceName: "{{ rl_mssql_instance_name }}"
  loop: "{{ rl_mssql_dbagent_operator }}"

- name: Configure Failsafe operator
  ansible.windows.win_dsc:
    resource_name: SqlAgentFailsafe
    Ensure: "Present"
    Name: "{{ item.name }}"
    ServerName: "localhost"
    Instancename: "{{ rl_mssql_instance_name }}"
    NotificationMethod: "NotifyEmail"
  loop: "{{ rl_mssql_dbagent_operator }}"
