---
- name: Create the standard set of maintenance jobs
  ansible.windows.win_dsc:
    resource_name: SqlScript
    Id: "MaintenanceJobs"
    SetFilePath: "{{ sql_install_temp_folder }}\\Set-StandardMaintenanceJobs.sql"
    GetFilePath: "{{ sql_install_temp_folder }}\\Get-StandardMaintenanceJobs.sql"
    TestFilePath: "{{ sql_install_temp_folder }}\\Test-StandardMaintenanceJobs.sql"
    Variable: "BackupDirectory={{ sql_install_backup_path }}"
    QueryTimeout: 600
    ServerName: "localhost"
    InstanceName: "{{ sql_install_instance_name }}"
    Encrypt: "Optional"
