---
# roles/sql_install/defaults/main.yml

# =============================================================================
# Disk Configuration
# =============================================================================
# Defines the disk layout for SQL Server data, logs, and TempDB.
sql_install_disks_to_format:
  - { number: 1, letter: "T", label: "TEMPDB" }
  - { number: 2, letter: "E", label: "DATA" }
  - { number: 3, letter: "F", label: "LOG" }

sql_install_prep_disks: "false"

# =============================================================================
# SQL Server Installation Media
# =============================================================================
# Specifies the location and version of the SQL Server installation media.
sql_install_share: "/home/username/ISO/"  # UNC path to the share or local path on the control node containing the ISO
sql_install_iso_source:
  - name: SQLServer2025-x64-ENU.iso
    version: SQL2025
    config: config2025.j2

sql_install_update_source:
  - name: updates
    version: SQL2025

# =============================================================================
# Core SQL Server Settings
# =============================================================================
# General settings for the SQL Server installation.
sql_install_edition: "Standard Developer"
sql_install_features: SQLENGINE,REPLICATION,FULLTEXT,IS
sql_install_instance_name: MSSQLSERVER
sql_install_sqlcollation: SQL_Latin1_General_CP1_CI_AS
sql_install_instance_port: 1433
sql_install_temp_folder: C:\temp

# =============================================================================
# Directory and Path Configuration
# =============================================================================
# Installation paths for SQL Server components.
sql_install_installshareddir: C:\Program Files\Microsoft SQL Server
sql_install_installsharedwowdir: C:\Program Files (x86)\Microsoft SQL Server
sql_install_instance_dir: C:\Program Files\Microsoft SQL Server
sql_install_installdb_path: "E:"
sql_install_userdb_path: E:\SQLDATA
sql_install_userdblog_path: F:\SQLDATA
sql_install_backup_path: T:\BACKUP

# =============================================================================
# Service Accounts and Security
# =============================================================================
# Configure service accounts and security settings.
sql_install_sql_svc_account:
# sql_install_sql_svc_password: 'notused'  # Default to "notused" if not defined
sql_install_agent_svc_account:
# sql_install_agent_svc_password: 'notused'  # Default to "notused" if not defined
sql_install_sql_svc_startup_type: "Automatic"
sql_install_agent_svc_startup_type: "Automatic"
sql_install_sysadminaccount: "Administrators"
sql_install_sapwd: ""  # Use Ansible Vault for production
sql_install_security_mode: "SQL"
sql_install_sqlsvcinstantfileinit: "true"

# =============================================================================
# Networking
# =============================================================================
# Network-related settings for SQL Server.
sql_install_tcp_enabled: "true"

# =============================================================================
# TempDB Configuration
# =============================================================================
# Settings for TempDB size, growth, and file locations.
sql_install_tempdb_path: T:\SQLDATA
sql_install_tempdblog_path: T:\SQLDATA
sql_install_tempdbfilecount: 4
sql_install_tempdbfilesize: 256
sql_install_tempdbfilegrowth: 256
sql_install_tempdblogfilesize: 256
sql_install_tempdblogfilegrowth: 64

# =============================================================================
# Integration Services (SSIS)
# =============================================================================
# Settings for SQL Server Integration Services.
sql_install_issvcaccount: NT Service\MsDtsServer160
sql_install_issvcpassword:
sql_install_install_ssisdb: "true"

# =================================s============================================
# Updates
# =============================================================================
# Windows and SQL Server update settings.
sql_install_enableupdates: "true"
sql_install_update_source_path: ""  # Dynamically set in install.yml

# =============================================================================
# Database Mail and Operators
# =============================================================================
# Configuration for Database Mail and SQL Agent operators.
sql_install_dbagent_operator:
  - name: DBATeam
    email: DBATeam@bogusdomain.com

sql_install_dbmail:
  - mailservername: "relayer.bogus.net"
    accountname: "DBMail"
    profilename: "DBMailProfile"
    description: "Default mail account and profile."
    emailaddress: "noreply@bogusdomain.com"
    replytoaddress: "noreply@bogusdomain.com"
    logginglevel: "Normal"
    tcpport: 25

# =============================================================================
# Miscellaneous
# =============================================================================
sql_install_source_path: ""  # Dynamically set in install.yml
sql_install_product_key: ""  # Use Ansible Vault for production