---
# defaults file for mssql
rl_mssql_edition: "Standard Developer"
rl_mssql_prep_disks: "true"
rl_mssql_temp_folder: C:\temp
rl_mssql_share: "/home/username/ISO/" # set this directory to your home directory
rl_mssql_enableupdates: "true"
rl_mssql_features: SQLENGINE,REPLICATION,FULLTEXT,IS
rl_mssql_instance_name: MSSQLSERVER
rl_mssql_installshareddir: C:\Program Files\Microsoft SQL Server
rl_mssql_installsharedwowdir: C:\Program Files (x86)\Microsoft SQL Server
rl_mssql_sqlcollation: SQL_Latin1_General_CP1_CI_AS
rl_mssql_svcaccount: NT Service\MSSQLSERVER # keeping it simple for Level 1.  Using builtin system accounts.  You can override the defaults at runtime.
rl_mssql_svcpassword: # This variable should be moved to /vars/sensitive_vars.yml if used.
rl_mssql_svcagentaccount: NT Service\SQLSERVERAGENT # keeping it simple for Level 1.  Using builtin system accounts.  You can override the defaults at runtime.
rl_mssql_svcagentpassword: #This variable should be moved to /vars/sensitive_vars.yml if used.
rl_mssql_installdb_path: "E:"
rl_mssql_instance_dir: C:\Program Files\Microsoft SQL Server
rl_mssql_userdb_path: E:\SQLDATA
rl_mssql_userdblog_path: F:\SQLDATA
rl_mssql_tempdb_path: T:\SQLDATA
rl_mssql_tempdblog_path: T:\SQLDATA
rl_mssql_backup_path: T:\BACKUP
rl_mssql_tempdblogfilesize: 256
rl_mssql_tempdblogfilegrowth: 64 # setting to 64mb to take advantage of IFI for log files in SQL Server 2022 and later.
rl_mssql_tempdbfilecount: 4
rl_mssql_tempdbfilesize: 256
rl_mssql_tempdbfilegrowth: 256
rl_mssql_issvcaccount: NT Service\MsDtsServer160
rl_mssql_issvcpassword:
rl_mssql_sqlsvcinstantfileinit: "true"
rl_mssql_instance_port: 1433
rl_mssql_install_ssisdb: "true"
rl_mssql_iso_source:
  - name: SQLServer2025-x64-ENU.iso
    version: SQL2025
    config: config2025.j2

rl_mssql_update_source:
  - name: updates
    version: SQL2025

# rl_mssql_iso_source:
#   - name: SQLServer2022_Dev.iso
#     version: SQL2022
#     config: config2022.j2

# rl_mssql_update_source:
#   - name: updates
#     version: SQL2022

rl_mssql_dbagent_operator:
  - name: DBATeam
    email: DBATeam@bogusdomain.com

rl_mssql_dbmail:
  - mailservername: "relayer.bogus.net"
    accountname: "DBMail"
    profilename: "DBMailProfile"
    description: "Default mail account and profile."
    emailaddress: "noreply@bogusdomain.com"
    replytoaddress: "noreply@bogusdomain.com"
    logginglevel: "Normal"
    tcpport: 25
