---
# the SqlServer powershell module is needed on the managed machines
- name: Identify the current AG primary
  ansible.windows.win_powershell:
    script: "{{ lookup('file', 'get_primary_replica.ps1') }}"
    parameters:
      SqlInstanceName: "{{ sql_instance_name }}"
      AgName: "{{ ag_name }}"
  register: ag_primary_info
  failed_when: not (ag_primary_info.result.Success | default(false))

- name: Set a fact with the primary hostname
  ansible.builtin.set_fact:
    ag_current_primary: "{{ ag_primary_info.result.PrimaryReplica }}"
  when: ag_primary_info.result.Success | default(false)

- name: Debug primary replica identification
  ansible.builtin.debug:
    msg: "{{ ag_primary_info.result.Message }}"
  when:
    - ag_primary_info.result.Success | default(false)
    - ansible_verbosity > 1
