---
# defaults file for mssql
# disk variables.
sql_install_disks_to_format:
  - { number: 1, letter: "T", label: "TEMPDB" }
  - { number: 2, letter: "E", label: "DATA" }
  - { number: 3, letter: "F", label: "LOG" }

sql_install_edition: "Standard Developer"
sql_install_prep_disks: "true"
sql_install_temp_folder: C:\temp
sql_install_share: "/home/lcampbell/level1/ISO/" # set this directory to the location of your ISO file.
sql_install_enableupdates: "true"
sql_install_features: SQLENGINE,REPLICATION,FULLTEXT,IS
sql_install_instance_name: MSSQLSERVER
sql_install_installshareddir: C:\Program Files\Microsoft SQL Server
sql_install_installsharedwowdir: C:\Program Files (x86)\Microsoft SQL Server
sql_install_sqlcollation: SQL_Latin1_General_CP1_CI_AS
sql_install_installdb_path: "E:"
sql_install_instance_dir: C:\Program Files\Microsoft SQL Server
sql_install_userdb_path: E:\SQLDATA
sql_install_userdblog_path: F:\SQLDATA
sql_install_tempdb_path: T:\SQLDATA
sql_install_tempdblog_path: T:\SQLDATA
sql_install_backup_path: T:\BACKUP
sql_install_tempdblogfilesize: 256
sql_install_tempdblogfilegrowth: 64 # setting to 64mb to take advantage of IFI for log files in SQL Server 2022 and later.
sql_install_tempdbfilecount: 4
sql_install_tempdbfilesize: 256
sql_install_tempdbfilegrowth: 256
sql_install_issvcaccount: NT Service\MsDtsServer160
sql_install_issvcpassword:
sql_install_sqlsvcinstantfileinit: "true"
sql_install_instance_port: 1433
sql_install_install_ssisdb: "true"
sql_install_iso_source:
  - name: SQLServer2025-x64-ENU.iso
    version: SQL2025
    config: config2025.j2

sql_install_update_source:
  - name: updates
    version: SQL2025

# sql_install_iso_source:
#   - name: SQLServer2022_Dev.iso
#     version: SQL2022
#     config: config2022.j2

# sql_install_update_source:
#   - name: updates
#     version: SQL2022

sql_install_dbagent_operator:
  - name: DBATeam
    email: DBATeam@bogusdomain.com

sql_install_dbmail:
  - mailservername: "relayer.bogus.net"
    accountname: "DBMail"
    profilename: "DBMailProfile"
    description: "Default mail account and profile."
    emailaddress: "noreply@bogusdomain.com"
    replytoaddress: "noreply@bogusdomain.com"
    logginglevel: "Normal"
    tcpport: 25

sql_install_powershell_modules_path: "{{ playbook_dir }}/"
