---
# defaults file for sql_ag_patch

# The remote path (e.g., a UNC share) where the SQL patch executable is located.
sql_patch_source: "//SRV1.SANDBOX.LOCAL/SQL_Updates/SQL2022/"

# The filename of the SQL patch executable.
sql_patch_filename: "SQLServer2022-KB5054531-x64.exe"

# The SHA256 checksum of the patch executable for verification.
sql_patch_checksum: "6E58447853AF96373BB838E7E7A0B41237CC8DAC2EBDCB78E13A268BE27B2694"

# Command-line arguments to pass to the patch executable.
# The `sql_instance_name_to_patch` variable is set dynamically in the prerequisites.yml file.
sql_patch_args: "/quiet /IAcceptSQLServerLicenseTerms /Action=Patch /InstanceName={{ sql_instance_name_to_patch }}"

# The name of the SQL Server Availability Group to patch.
ag_name: "SANDBOXAG"

# Whether to patch the primary replica. If set to false, the role will patch the secondaries and then stop.
patch_primary: true

# Whether to fail back to the original primary after patching is complete.
sql_ag_failback: true

# Whether to remove the SqlServer module if it was installed by this role.
remove_sqlserver_module: true

# Whether to reboot secondary replicas after patching.
reboot_secondary: true

# The time in seconds to wait for the reboot to complete.
sql_reboot_timeout: 1800

# A temporary folder on the target nodes for staging files.
sql_patch_temp_folder: "C:/temp/"

# The TCP port SQL Server is listening on. Used to verify service availability after a reboot.
sql_port: 1433

# The exact version string of SQL Server after the patch is applied. This is used for verification.
desired_sql_version: "16.0.4195" # "16.0.4175" # "16.0.4185"