---
- name: Uninstall SqlServer module on failure
  community.windows.win_psmodule:
    name: SqlServer
    state: absent
  when:
    - remove_sqlserver_module
    - sqlserver_module_was_installed_by_role

- name: Cleanup temporary files
  ansible.windows.win_file:
    path: "{{ sql_patch_temp_folder }}"
    state: absent
