---
galaxy_info:
  author: Luke Campbell <Luke.Campbell@automatesql.com>
  description: A role to manage PowerShell modules on Windows hosts.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Windows
      versions:
        - all

collections:
  - community.windows
