---
- name: Create the DBA database
  ansible.windows.win_dsc:
    resource_name: SqlDatabase
    Ensure: "Present"
    Name: "{{ item }}"
    OwnerName: "sa"
    ServerName: "localhost"
    InstanceName: "{{ sql_install_instance_name }}"
  loop:
    - DBA

- name: Deploy objects to the DBA database
  ansible.windows.win_dsc:
    resource_name: SqlScript
    Id: "DBAObjects"
    SetFilePath: "{{ sql_install_temp_folder }}\\Set-DBA.sql"
    GetFilePath: "{{ sql_install_temp_folder }}\\Get-DBA.sql"
    TestFilePath: "{{ sql_install_temp_folder }}\\Test-DBA.sql"
    QueryTimeout: 600
    ServerName: "localhost"
    InstanceName: "{{ sql_install_instance_name }}"
    Encrypt: "Optional"
