---
- name: Firewall rule to allow SQL Server access
  community.windows.win_firewall_rule:
    name: "{{ sql_install_instance_name }}"
    localport: "{{ sql_install_instance_port }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true
