name: Publish to Ansible Galaxy

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Get version from release tag
        id: get_version
        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed -e 's/^v//')" >> $GITHUB_ENV

      - name: Publish to Galaxy
        uses: ansible/ansible-galaxy-action@v1.2.0
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
          galaxy_version: ${{ env.VERSION }}
